# This is a basic workflow to help you get started with Actions

name: Move assigned issued into To do

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues: 
    types: [assigned]
  pull_request:
    types: [assigned]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: GitHub Project Automation+
      uses: alex-page/github-project-automation-plus@v0.2.4
      with:
        # The GH_TOKEN secret can be passed in using 
       repo-token: ${{ secrets.GHTOKEN }}
        # The name of the GitHub Project
       project: "鐵人賽 30 天從 Swift 學會 Objective C"
      # The name of the column to move the issue or pull request to
       column: "未完成"
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@v1.3
      env:
        GITHUB_TOKEN: ${{secrets.GHTOKEN}}
        branchName: 'issues/${issue.number}/${issue.title}'
        slient: false
        autoCloseIssue: true
